In [1]:
import pandas as pd
import numpy as np

In [2]:
df_books = pd.read_csv('/content/bestsellers-with-categories.csv', sep=',',header=0)

In [3]:
df_books.head(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

Realizar filtrado por condiciones

In [8]:
##Nos retornará valores booleanos y lo asignaremos a una variable
mayor_2016 = df_books['Year'] > 2016

In [9]:
#Ahora podemos llamar al objeto df_books y pasarle como lista los valores que queremos visualizar
df_books[mayor_2016]

,Name,Author,User Rating,Reviews,Price,Year,Genre
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction
...,...,...,...,...,...,...,...
544,Wonder,R. J. Palacio,4.8,21625,9,2017,Fiction
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [12]:
#Podemos obtener el mismo resultado realizando de la siguiente manera
df_books[df_books['Year'] > 2016]

,Name,Author,User Rating,Reviews,Price,Year,Genre
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction
...,...,...,...,...,...,...,...
544,Wonder,R. J. Palacio,4.8,21625,9,2017,Fiction
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [13]:
#Si queremos filtrar por una columna que contenga algun texto, ejecutamos la siguiente línea de código
df_books[df_books['Author'].str.contains('Peterson')]

,Name,Author,User Rating,Reviews,Price,Year,Genre
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction

In [24]:
#Para evaluar más de una condición, lo lograremos colocando cada una de ellas entre paréntesis
df_books[(df_books['Year'] > 2017) & (df_books['User Rating'] > 4.6) & (df_books['Genre'] == 'Non Fiction') & (df_books['Reviews'] > 15000)]

,Name,Author,User Rating,Reviews,Price,Year,Genre
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
32,Becoming,Michelle Obama,4.8,61133,11,2018,Non Fiction
33,Becoming,Michelle Obama,4.8,61133,11,2019,Non Fiction
44,Can't Hurt Me: Master Your Mind and Defy the Odds,David Goggins,4.8,16244,18,2019,Non Fiction
97,Educated: A Memoir,Tara Westover,4.7,28729,15,2018,Non Fiction
98,Educated: A Memoir,Tara Westover,4.7,28729,15,2019,Non Fiction
114,First 100 Words,Roger Priddy,4.7,17323,4,2018,Non Fiction
170,How to Win Friends & Influence People,Dale Carnegie,4.7,25001,11,2018,Non Fiction
231,Milk and Honey,Rupi Kaur,4.7,17739,8,2018,Non Fiction
293,School Zone - Big Preschool Workbook - Ages 4 ...,School Zone,4.8,23047,6,2018,Non Fiction
294,School Zone - Big Preschool Workbook - Ages 4 ...,School Zone,4.8,23047,6,2019,Non Fiction
328,The 5 Love Languages: The Secret to Love that ...,Gary Chapman,4.8,25554,8,2018,Non Fiction
329,The 5 Love Languages: The Secret to Love that ...,Gary Chapman,4.8,25554,8,2019,Non Fiction
379,The Four Agreements: A Practical Guide to Pers...,Don Miguel Ruiz,4.7,23308,6,2018,Non Fiction
380,The Four Agreements: A Practical Guide to Pers...,Don Miguel Ruiz,4.7,23308,6,2019,Non Fiction

In [20]:
#Lograremos asignar filtros a variables y colocar nuestras condiciones con respecto a estas
year_2010 = df_books['Year'] == 2010
author_book = df_books['Author'] == 'Mark Twain'
#Nos arroja como resultado todos los libros del 2010 escritos por Mark Twain
df_books[year_2010 & author_book]

,Name,Author,User Rating,Reviews,Price,Year,Genre
27,"Autobiography of Mark Twain, Vol. 1",Mark Twain,4.2,491,14,2010,Non Fiction

#Negando las condiciones utilizando la virgulilla

In [22]:
"""Si al códgio anterior aplicamos una virgulilla (~) nos arrojará como resultado aquellos que no cumplan esa condición, es decir, todos quellos libros publicados
en el 2010 que no fueron escritos por el autor Mark Twain""" 
df_books[year_2010 & ~author_book]

,Name,Author,User Rating,Reviews,Price,Year,Genre
11,A Patriot's History of the United States: From...,Larry Schweikart,4.6,460,2,2010,Non Fiction
31,"Barefoot Contessa, How Easy Is That?: Fabulous...",Ina Garten,4.7,615,21,2010,Non Fiction
39,"Broke: The Plan to Restore Our Trust, Truth an...",Glenn Beck,4.5,471,8,2010,Non Fiction
46,Catching Fire (The Hunger Games),Suzanne Collins,4.7,22614,11,2010,Fiction
51,Crazy Love: Overwhelmed by a Relentless God,Francis Chan,4.7,1542,14,2010,Non Fiction
56,Cutting for Stone,Abraham Verghese,4.6,4866,11,2010,Fiction
61,Dead in the Family (Sookie Stackhouse/True Blo...,Charlaine Harris,4.3,1924,8,2010,Fiction
67,Decision Points,George W. Bush,4.6,2137,17,2010,Non Fiction
68,"Delivering Happiness: A Path to Profits, Passi...",Tony Hsieh,4.6,1651,15,2010,Non Fiction
90,Drive: The Surprising Truth About What Motivat...,Daniel H. Pink,4.5,2525,16,2010,Non Fiction
115,Food Rules: An Eater's Manual,Michael Pollan,4.4,1555,9,2010,Non Fiction
117,"Game Change: Obama and the Clintons, McCain an...",John Heilemann,4.4,1215,9,2010,Non Fiction
121,George Washington's Sacred Fire,Peter A. Lillback,4.5,408,20,2010,Non Fiction
140,Good to Great: Why Some Companies Make the Lea...,Jim Collins,4.5,3457,14,2010,Non Fiction
217,Life,Keith Richards,4.5,2752,18,2010,Non Fiction
218,Little Bee: A Novel,Chris Cleave,4.1,1467,10,2010,Fiction
236,Mockingjay (The Hunger Games),Suzanne Collins,4.5,26741,8,2010,Fiction
261,Outliers: The Story of Success,Malcolm Gladwell,4.6,10426,20,2010,Non Fiction
264,Percy Jackson and the Olympians Paperback Boxe...,Rick Riordan,4.8,548,2,2010,Fiction
272,Publication Manual of the American Psychologic...,American Psychological Association,4.5,8580,46,2010,Non Fiction
284,Radical: Taking Back Your Faith from the Ameri...,David Platt,4.7,1985,9,2010,Non Fiction
292,Sarah's Key,Tatiana de Rosnay,4.6,3619,10,2010,Fiction
296,Sh*t My Dad Says,Justin Halpern,4.7,1265,11,2010,Non Fiction
305,StrengthsFinder 2.0,Gallup,4.0,5069,17,2010,Non Fiction
314,Switch: How to Change Things When Change Is Hard,Chip Heath,4.6,1907,13,2010,Non Fiction
316,Teach Like a Champion: 49 Techniques that Put ...,Doug Lemov,4.4,637,20,2010,Non Fiction
320,The 5 Love Languages: The Secret to Love That ...,Gary Chapman,4.7,3477,28,2010,Non Fiction
340,The Art of Racing in the Rain: A Novel,Garth Stein,4.7,11813,10,2010,Fiction
342,The Big Short: Inside the Doomsday Machine,Michael Lewis,4.7,3536,17,2010,Non Fiction
357,The Confession: A Novel,John Grisham,4.3,3523,13,2010,Fiction
359,The Daily Show with Jon Stewart Presents Earth...,Jon Stewart,4.4,440,11,2010,Non Fiction
370,The Five Dysfunctions of a Team: A Leadership ...,Patrick Lencioni,4.6,3207,6,2010,Non Fiction
384,The Girl Who Kicked the Hornet's Nest (Millenn...,Stieg Larsson,4.7,7747,14,2010,Fiction
386,The Girl Who Played with Fire (Millennium Series),Stieg Larsson,4.7,7251,9,2010,Fiction
389,The Girl with the Dragon Tattoo (Millennium Se...,Stieg Larsson,4.4,10559,2,2010,Fiction
403,The Help,Kathryn Stockett,4.8,13871,6,2010,Fiction
407,The Hunger Games,Suzanne Collins,4.7,32122,14,2010,Fiction
412,The Immortal Life of Henrietta Lacks,Rebecca Skloot,4.7,9289,13,2010,Non Fiction
419,The Last Olympian (Percy Jackson and the Olymp...,Rick Riordan,4.8,4628,7,2010,Fiction
428,"The Lost Hero (Heroes of Olympus, Book 1)",Rick Riordan,4.8,4506,14,2010,Fiction
439,The Official SAT Study Guide,The College Board,4.4,1201,40,2010,Non Fiction
456,"The Red Pyramid (The Kane Chronicles, Book 1)",Rick Riordan,4.6,2186,12,2010,Fiction
457,The Road to Serfdom: Text and Documents--The D...,F. A. Hayek,4.6,1204,14,2010,Non Fiction
461,The Short Second Life of Bree Tanner: An Eclip...,Stephenie Meyer,4.6,2122,0,2010,Fiction
474,"The Ugly Truth (Diary of a Wimpy Kid, Book 5)",Jeff Kinney,4.8,3796,12,2010,Fiction
499,Three Cups of Tea: One Man's Mission to Promot...,Greg Mortenson,4.3,3319,11,2010,Non Fiction
511,"Towers of Midnight (Wheel of Time, Book Thirteen)",Robert Jordan,4.8,2282,21,2010,Fiction
515,"Unbroken: A World War II Story of Survival, Re...",Laura Hillenbrand,4.8,29673,16,2010,Non Fiction
539,Women Food and God: An Unexpected Path to Almo...,Geneen Roth,4.2,1302,11,2010,Non Fiction