In [1]:
import pandas as pd
import numpy as np

In [2]:
dictionary = {'Col1': [1,2,3,np.nan],
 'Col2': [ 4,np.nan,6,7],
 'Col3': ['a','b','c',None]}

In [3]:
#Creamos un dataframe basado en el diccionario arriba creado
df = pd.DataFrame(dictionary)

In [4]:
df

   Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

Manejo de valores nulos

In [5]:
#isnull() nos muestra valores booleanos para indicarnos valores nulos
df.isnull()

    Col1   Col2   Col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [7]:
#Si deseamos manejar valores numericos lo realizamos de la siguiente manera donde los ceros nos indicaran que existen datos, mientras que, los 1 que son valores nulos
df.isnull() * 1

   Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [8]:
#Podemos cambiar su valor por alguna palabra que eligamos
df.fillna('Mising')

     Col1    Col2    Col3
0     1.0     4.0       a
1     2.0  Mising       b
2     3.0     6.0       c
3  Mising     7.0  Mising

In [9]:
#Para valores númericos podemos optar por llenar los datos con operaciones como la media
df.fillna(df.mean())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

   Col1      Col2  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

In [11]:
#Para valores numericos interpolate asumirá que es un serie y llenará el campo nulo con el valor siguiente
df.interpolate()

   Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [12]:
#En otra instancia, podemos optar por borrar los valores nulos
df.dropna()

   Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c

In [13]:
#Para eliminar valores nulos de una columna en específico utilizamos la sentencia subset
df.dropna(subset=['Col2'])

   Col1  Col2  Col3
0   1.0   4.0     a
2   3.0   6.0     c
3   NaN   7.0  None